import { cloneElement, useEffect, useId, useRef, useState } from 'react';
import { Check, X, Download, Plus, RefreshCw, PackageOpen, AlertCircle } from 'lucide-react';
import { useWorkspace } from '../lib/context';
import { exportCSV, label } from '../lib/format';

export function Brand(){return <div className="brand"><svg viewBox="0 0 44 44" aria-hidden="true"><circle cx="22" cy="22" r="18"/><circle cx="22" cy="22" r="12"/><circle cx="22" cy="22" r="5"/><path d="M4 22h7m22 0h7M22 4v7m0 22v7"/></svg><div><strong>Accurate Rings<span className="brand-period">.</span></strong><small>Manufacturing workspace</small></div></div>;}
export function PageHeader({eyebrow='OPERATIONS',title,description,children}){return <div className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-description">{description}</p></div><div className="page-actions">{children}</div></div>;}
export function ActionButton({children,onClick,primary=false,icon='plus',...props}){const Icon=icon==='refresh'?RefreshCw:icon==='download'?Download:Plus;return <button className={'button '+(primary?'button-primary':'button-secondary')} onClick={onClick} {...props}><Icon size={16}/>{children}</button>;}
export function ExportButton({name,columns,rows}){const {notify}=useWorkspace();return <ActionButton icon="download" onClick={()=>{exportCSV(name,columns,rows);notify('CSV exported');}} disabled={!rows.length}>Export CSV</ActionButton>;}
export function Metric({title,value,detail,icon:Icon,tone='teal'}){return <article className="metric"><div className="metric-top"><span>{title}</span><div className={'metric-icon '+tone}>{Icon&&<Icon size={18}/>}</div></div><strong className="metric-value">{value}</strong><p>{detail}</p></article>;}
export function Status({value}){return <span className={'status status-'+(value||'pending').replaceAll('_','-')}>{label(value)}</span>;}
export function Panel({title,subtitle,actions,children,className=''}){return <section className={'panel '+className}><div className="panel-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{actions}</div>{children}</section>;}
export function Empty({title='No records to show',description='Try another filter or add a record to get started.'}){return <div className="empty"><PackageOpen size={32}/><strong>{title}</strong><p>{description}</p></div>;}
export function Table({columns,rows,rowKey,caption='Workspace records',onRow}){return <div className="table-wrap"><table><caption className="sr-only">{caption}</caption><thead><tr>{columns.map(c=><th key={c.key} scope="col" className={c.className||''}>{c.title}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row[rowKey]} className={onRow?'clickable-row':''}>{columns.map((c,index)=><td key={c.key} className={c.className||''}>{onRow&&index===0?<button className="table-link" onClick={()=>onRow(row)}>{c.render?c.render(row):row[c.key]}</button>:c.render?c.render(row):row[c.key]}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty/>}</div>;}
export function Field({label:fieldLabel,children,...props}){const id=useId();return <label className="field" htmlFor={id}><span>{fieldLabel}</span>{children?cloneElement(children,{id}):<input id={id} {...props}/>}</label>;}
export function Select({label:fieldLabel,options,...props}){const id=useId();return <label className="field" htmlFor={id}><span>{fieldLabel}</span><select id={id} {...props}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;}
export function FormDialog({open,title,description,action,children,onClose,initialPayload={},submitLabel='Save changes'}){
  const dialog=useRef(null),formId=useId();const [error,setError]=useState('');const {perform,busy}=useWorkspace();
  useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
  const submit=async event=>{event.preventDefault();setError('');try{await perform(action,{...initialPayload,...Object.fromEntries(new FormData(event.currentTarget))});onClose();}catch(e){setError(e.message);}};
  return <dialog ref={dialog} className="modal" onCancel={event=>{event.preventDefault();if(!busy)onClose();}}><div className="modal-heading"><div><h2>{title}</h2><p>{description}</p></div><button className="icon-button" aria-label="Close dialog" onClick={onClose} disabled={busy}><X size={20}/></button></div><form id={formId} onSubmit={submit} className="form-grid">{children}{error&&<p className="form-error" role="alert"><AlertCircle size={16}/>{error}</p>}</form><div className="modal-footer"><button className="button button-secondary" onClick={onClose} disabled={busy}>Cancel</button><button className="button button-primary" type="submit" form={formId} disabled={busy}>{busy?'Saving…':submitLabel}<Check size={16}/></button></div></dialog>;
}
export function ConfirmDialog({open,title,description,onConfirm,onClose}){const ref=useRef(null);const [error,setError]=useState('');const {busy}=useWorkspace();useEffect(()=>{if(open)ref.current?.showModal();else ref.current?.close();},[open]);return <dialog ref={ref} className="modal modal-small" onCancel={onClose}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close"><X size={18}/></button></div><p className="confirm-copy">{description}</p>{error&&<p className="form-error">{error}</p>}<div className="modal-footer"><button className="button button-secondary" onClick={onClose}>Cancel</button><button className="button button-primary" disabled={busy} onClick={async()=>{try{await onConfirm();onClose();}catch(e){setError(e.message);}}}>{busy?'Saving…':'Confirm'}</button></div></dialog>;}
