import { lazy, Suspense, useMemo, useRef, useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Search, ShoppingBag, Boxes, Factory, Gauge, ShieldCheck, Truck, TrendingUp, Clock3, CircleCheck, ChevronLeft, ChevronRight, X, PackageCheck, IndianRupee } from 'lucide-react';
import { useWorkspace } from '../lib/context';
import { PageHeader, Metric, Panel, Status, Table, Field, Select, FormDialog, ConfirmDialog, ActionButton, ExportButton } from '../components/UI';
import { count, rupees, shortMoney, date, label } from '../lib/format';
import { COST_FIELDS, ORDER_STAGES } from '../../../shared/workspace.mjs';
const DeliveryMap=lazy(()=>import('../components/DeliveryMap'));
const definitions={
  orders:{title:'Orders',description:'Customer commitments, quantities and delivery dates in one place.',eyebrow:'CUSTOMER OPERATIONS',add:'New order',action:'createOrder',key:'order_id'},
  inventory:{title:'Inventory',description:'Available stock, reserved quantities and reorder levels.',eyebrow:'MATERIAL CONTROL',add:'Add stock item',action:'createStockItem',key:'inventory_id'},
  production:{title:'Production',description:'Plan batches, record output and release completed lots for inspection.',eyebrow:'SHOP FLOOR',add:'Schedule batch',action:'createBatch',key:'production_id'},
  machines:{title:'Machine usage',description:'Track machine availability, running hours and energy consumption.',eyebrow:'SHOP FLOOR',add:'Log machine hours',action:'logRuntime',key:'usage_id'},
  quality:{title:'Quality control',description:'Inspect completed batches and trace accepted, reworked and scrapped rings.',eyebrow:'QUALITY ASSURANCE',key:'inspection_id'},
  dispatch:{title:'Dispatch & delivery',description:'Pack inspected rings, confirm transport and record completed deliveries.',eyebrow:'LOGISTICS',add:'Create dispatch',action:'createDispatch',key:'dispatch_id'},
  finance:{title:'Cost & margin',description:'Compare order revenue with a complete, consistent cost sheet.',eyebrow:'FINANCIAL CONTROL',add:'Record order costs',action:'updateCosts',key:'profit_id'},
};
const sum=(rows,key)=>rows.reduce((total,row)=>total+Number(row[key]||0),0);
export default function Records({kind}){const [params]=useSearchParams();return <RecordPage key={kind+':'+(params.get('q')||'')} kind={kind} initialSearch={params.get('q')||''}/>;}
function OrderDetails({order,customer,onClose}){const ref=useRef(null);useEffect(()=>{ref.current?.showModal();},[]);const step=ORDER_STAGES.indexOf(order.status);return <dialog ref={ref} className="modal order-detail" onCancel={onClose}><div className="modal-heading"><div><p className="eyebrow">ORDER DETAILS</p><h2>ORD-{order.order_id}</h2></div><button className="icon-button" aria-label="Close order details" onClick={onClose}><X size={20}/></button></div><div className="order-detail-body"><div className="detail-summary"><h3>{customer?.company_name}</h3><Status value={order.status}/></div><p className="muted">{customer?.customer_name} · {customer?.location}</p><div className="detail-grid"><div><span>Product</span><strong>{order.product_name}</strong></div><div><span>Material grade</span><strong>{order.grade}</strong></div><div><span>Order quantity</span><strong>{count(order.quantity)} rings</strong></div><div><span>Order value</span><strong>{rupees(order.total_amount)}</strong></div><div><span>Created</span><strong>{date(order.order_date)}</strong></div><div><span>Expected delivery</span><strong>{date(order.expected_delivery_date)}</strong></div></div><h3 className="detail-section-title">Manufacturing progress</h3><ol className="order-timeline">{ORDER_STAGES.map((s,i)=><li key={s} className={i<=step?'done':''}><span>{i<step?<CircleCheck size={17}/>:i+1}</span><div><strong>{label(s)}</strong>{i===step&&<small>Current stage</small>}</div></li>)}</ol>{order.notes&&<div className="detail-notes"><strong>Order notes</strong><p>{order.notes}</p></div>}</div><div className="modal-footer"><button className="button button-primary" onClick={onClose}>Done</button></div></dialog>;}
function RecordPage({kind,initialSearch}){
  const {state,user,perform,busy,notify}=useWorkspace();const config=definitions[kind];const [search,setSearch]=useState(initialSearch),[filter,setFilter]=useState('all'),[page,setPage]=useState(0),[modal,setModal]=useState(null),[detail,setDetail]=useState(null),[confirmation,setConfirmation]=useState(null),[chosenOrder,setChosenOrder]=useState(''),[chosenProduct,setChosenProduct]=useState(state.products[0]?.name||'');
  const canWrite=user.role!=='customer';const today=new Date().toISOString().slice(0,10);const customerFor=id=>state.customers.find(c=>c.customer_id===id);const orderFor=id=>state.orders.find(o=>o.order_id===id);const machineFor=id=>state.machines.find(m=>m.machine_id===id);
  const approvedFor=id=>state.inspections.filter(i=>i.order_id===id).reduce((s,i)=>s+i.accepted_rings+i.reworked_quantity,0)-state.dispatches.filter(d=>d.order_id===id).reduce((s,d)=>s+d.packed_quantity,0);
  const remainingFor=id=>{const order=orderFor(id);return (order?.quantity||0)+sum(state.inspections.filter(i=>i.order_id===id),'scrap_quantity')-sum(state.production.filter(p=>p.order_id===id),'target_quantity');};
  const batchOptions=state.orders.filter(o=>!['dispatched','delivered'].includes(o.status)&&remainingFor(o.order_id)>0);
  const dispatchOptions=state.orders.filter(o=>approvedFor(o.order_id)>0&&o.status!=='delivered');
  const formOrders=modal?.action==='createBatch'?batchOptions:modal?.action==='createDispatch'?dispatchOptions:state.orders;
  const selectedOrder=Number(chosenOrder||formOrders[0]?.order_id||0);
  const tableRows=useMemo(()=>{if(kind==='orders')return [...state.orders];if(kind==='inventory')return state.inventory.map(i=>({...i,stock_status:i.available_quantity-i.reserved_quantity<=i.low_stock_limit?'low_stock':'available'}));if(kind==='production')return [...state.production];if(kind==='machines')return [...state.machineUsage];if(kind==='quality')return [...state.inspections];if(kind==='dispatch')return [...state.dispatches];return [...state.finance];},[kind,state]);
  const filtered=tableRows.filter(row=>{const order=kind==='orders'?row:orderFor(row.order_id);const haystack=Object.values(row).join(' ')+' '+customerFor(order?.customer_id)?.company_name+' '+order?.product_name+' '+machineFor(row.machine_id)?.machine_name;const status=kind==='inventory'?row.stock_status:kind==='dispatch'?row.delivery_status:row.status;return haystack.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||status===filter);}).sort((a,b)=>b[config.key]-a[config.key]);
  const pageCount=Math.max(1,Math.ceil(filtered.length/8)),currentPage=Math.min(page,pageCount-1);const shown=filtered.slice(currentPage*8,currentPage*8+8);
  const open=(action,row=null)=>{setChosenOrder('');setModal({action,row});};
  const rowButton=(title,action,row)=><button className="table-action" onClick={()=>open(action,row)} disabled={busy}>{title}</button>;
  const columns={
    orders:[{key:'order_id',title:'Order',render:o=><div className="cell-stack"><span className="record-id">ORD-{o.order_id}</span>{o.priority==='urgent'&&<span className="priority-mark">Priority</span>}</div>},{key:'company',title:'Customer / product',render:o=><div className="cell-stack"><strong>{customerFor(o.customer_id)?.company_name}</strong><span>{o.product_name}</span></div>},{key:'quantity',title:'Quantity',render:o=>count(o.quantity)+' pcs'},{key:'total_amount',title:'Order value',className:'numeric',render:o=>rupees(o.total_amount)},{key:'due',title:'Delivery',render:o=><span className={o.expected_delivery_date<today&&o.status!=='delivered'?'text-danger':''}>{date(o.expected_delivery_date)}</span>},{key:'status',title:'Stage',render:o=><Status value={o.status}/>}],
    inventory:[{key:'sku',title:'Item / SKU',render:i=><div className="cell-stack"><strong>{i.item_name}</strong><span className="mono">{i.sku}</span></div>},{key:'type',title:'Category',render:i=>label(i.item_type)},{key:'stock',title:'Available',className:'numeric',render:i=><strong>{count(i.available_quantity-i.reserved_quantity)} <span className="muted">{i.unit}</span></strong>},{key:'reserved',title:'Reserved',className:'numeric',render:i=>count(i.reserved_quantity)+' '+i.unit},{key:'reorder',title:'Reorder at',className:'numeric',render:i=>count(i.low_stock_limit)+' '+i.unit},{key:'location',title:'Location'},{key:'status',title:'Status',render:i=><Status value={i.stock_status}/>}],
    production:[{key:'production_id',title:'Batch',render:p=><span className="record-id">LOT-{p.production_id}</span>},{key:'order',title:'Order / product',render:p=><div className="cell-stack"><strong>ORD-{p.order_id}</strong><span>{orderFor(p.order_id)?.product_name}</span></div>},{key:'machine',title:'Machine / operator',render:p=><div className="cell-stack"><strong>{machineFor(p.machine_id)?.machine_name}</strong><span>{p.operator_name}</span></div>},{key:'output',title:'Produced / target',render:p=><div className="output-cell"><span>{count(p.quantity_produced)} <small>/ {count(p.target_quantity)}</small></span><div className="progress-track"><div style={{width:Math.min(100,p.quantity_produced/p.target_quantity*100)+'%'}}/></div></div>},{key:'date',title:'Updated',render:p=>date(p.production_date)},{key:'status',title:'Status',render:p=><Status value={p.status}/>}],
    machines:[{key:'usage_id',title:'Record',render:u=><span className="record-id">MU-{u.usage_id}</span>},{key:'machine',title:'Machine',render:u=><div className="cell-stack"><strong>{machineFor(u.machine_id)?.machine_name}</strong><span>{machineFor(u.machine_id)?.department}</span></div>},{key:'operator_name',title:'Operator'},{key:'order',title:'Order',render:u=>'ORD-'+u.order_id},{key:'date',title:'Date',render:u=>date(u.start_time)},{key:'hours',title:'Runtime',className:'numeric',render:u=>u.running_hours.toFixed(2)+' h'},{key:'energy',title:'Energy',className:'numeric',render:u=>(u.running_hours*(machineFor(u.machine_id)?.power_rating_kw||0)).toFixed(2)+' kWh'}],
    quality:[{key:'inspection_id',title:'Inspection',render:i=><div className="cell-stack"><span className="record-id">QC-{i.inspection_id}</span><span>LOT-{i.production_id}</span></div>},{key:'order',title:'Order / inspector',render:i=><div className="cell-stack"><strong>ORD-{i.order_id}</strong><span>{i.inspector_name||'Awaiting inspector'}</span></div>},{key:'checked',title:'Checked',className:'numeric',render:i=>count(i.quantity_checked)},{key:'accepted',title:'Accepted',className:'numeric',render:i=><span className="text-success">{count(i.accepted_rings)}</span>},{key:'faulty',title:'Faulty',className:'numeric',render:i=><span className={i.faulty_rings?'text-danger':''}>{count(i.faulty_rings)}</span>},{key:'reworked',title:'Reworked / scrap',className:'numeric',render:i=>count(i.reworked_quantity)+' / '+count(i.scrap_quantity)},{key:'status',title:'Status',render:i=><Status value={i.status}/>}],
    dispatch:[{key:'dispatch_id',title:'Consignment',render:d=><div className="cell-stack"><span className="record-id">DSP-{d.dispatch_id}</span><span>ORD-{d.order_id}</span></div>},{key:'destination',title:'Customer / destination',render:d=><div className="cell-stack"><strong>{customerFor(orderFor(d.order_id)?.customer_id)?.company_name}</strong><span>{customerFor(orderFor(d.order_id)?.customer_id)?.location}</span></div>},{key:'quantity',title:'Packed',className:'numeric',render:d=>count(d.packed_quantity)+' pcs'},{key:'transport',title:'Transport / reference',render:d=><div className="cell-stack"><strong>{d.transport_details}</strong><span className="mono">{d.tracking_reference}</span></div>},{key:'date',title:'Dispatched / delivered',render:d=><div className="cell-stack"><strong>{date(d.dispatch_date)}</strong><span>{date(d.delivery_date)}</span></div>},{key:'status',title:'Status',render:d=><Status value={d.delivery_status}/>}],
    finance:[{key:'order_id',title:'Order / customer',render:f=><div className="cell-stack"><span className="record-id">ORD-{f.order_id}</span><span>{customerFor(orderFor(f.order_id)?.customer_id)?.company_name}</span></div>},{key:'selling_amount',title:'Revenue',className:'numeric',render:f=>rupees(f.selling_amount)},{key:'total_cost',title:'Total cost',className:'numeric',render:f=>rupees(f.total_cost)},{key:'profit_or_loss',title:'Contribution',className:'numeric',render:f=><strong className={f.profit_or_loss>=0?'text-success':'text-danger'}>{rupees(f.profit_or_loss)}</strong>},{key:'margin',title:'Margin',className:'numeric',render:f=>f.selling_amount?(f.profit_or_loss/f.selling_amount*100).toFixed(1)+'%':'—'},{key:'status',title:'Recognition',render:f=><Status value={f.status}/>}],
  }[kind];
  if(kind==='orders')columns.push({key:'action',title:'',render:o=><button className="table-action" onClick={()=>setDetail(o)}>View details</button>});
  if(canWrite&&kind==='inventory')columns.push({key:'action',title:'',render:i=>rowButton('Adjust stock','adjustStock',i)});
  if(canWrite&&kind==='production')columns.push({key:'action',title:'',render:p=>p.status==='in_progress'?rowButton('Record output','updateBatch',p):<span className="muted">Complete</span>});
  if(canWrite&&kind==='quality')columns.push({key:'action',title:'',render:i=>i.status==='pending'?rowButton('Inspect batch','recordInspection',i):<span className="muted">Recorded</span>});
  if(canWrite&&kind==='dispatch')columns.push({key:'action',title:'',render:d=>d.delivery_status==='delivered'?<CircleCheck size={19} className="text-success"/>:<button className="table-action" disabled={busy} onClick={()=>setConfirmation(d)}>{d.delivery_status==='packed'?'Confirm dispatch':'Mark delivered'}</button>});
  if(kind==='finance')columns.push({key:'action',title:'',render:f=>rowButton('Edit costs','updateCosts',f)});
  const checked=sum(state.inspections,'quantity_checked'),accepted=sum(state.inspections,'accepted_rings');const metrics={
    orders:[['Open orders',state.orders.filter(o=>o.status!=='delivered').length,'Manufacturing and logistics',ShoppingBag],['Booked order value',shortMoney(sum(state.orders,'total_amount')),'All orders in this workspace',IndianRupee],['Due in 7 days',state.orders.filter(o=>o.status!=='delivered'&&new Date(o.expected_delivery_date)-new Date(today)<=7*86400000).length,'Review upcoming commitments',Clock3],['Delivered',state.orders.filter(o=>o.status==='delivered').length,'Completed order quantities',PackageCheck]],
    inventory:[['Stock items',state.inventory.length,'Distinct materials and products',Boxes],['Reorder alerts',state.inventory.filter(i=>i.available_quantity-i.reserved_quantity<=i.low_stock_limit).length,'Available after reservations',Clock3],['Finished rings',count(sum(state.inventory.filter(i=>i.item_type==='finished_product'&&i.unit==='pcs'),'available_quantity')),'Pieces in finished goods',PackageCheck],['Storage locations',new Set(state.inventory.map(i=>i.location)).size,'Locations represented in stock',Factory]],
    production:[['Active batches',state.production.filter(p=>p.status==='in_progress').length,'Currently on the shop floor',Factory],['Total produced',count(sum(state.production,'quantity_produced')),'Recorded bearing rings',Boxes],['Batch targets',count(sum(state.production,'target_quantity')),'Allocated order quantities',ShoppingBag],['Completed batches',state.production.filter(p=>p.status==='completed').length,'Released to inspection',CircleCheck]],
    machines:[['Machines available',state.machines.filter(m=>m.status==='active').length,state.machines.length+' machines configured',Gauge],['Running hours',sum(state.machineUsage,'running_hours').toFixed(1)+' h','Across recorded usage',Clock3],['Energy consumed',state.machineUsage.reduce((s,u)=>s+u.running_hours*(machineFor(u.machine_id)?.power_rating_kw||0),0).toFixed(1)+' kWh','Runtime × rated machine power',TrendingUp],['Under maintenance',state.machines.filter(m=>m.status==='maintenance').length,'Unavailable for scheduling',Factory]],
    quality:[['Rings inspected',count(checked),'Completed inspections only',ShieldCheck],['First-pass yield',checked?(accepted/checked*100).toFixed(1)+'%':'—','Accepted before rework',CircleCheck],['Faulty rings',count(sum(state.inspections,'faulty_rings')),'Traceable to inspection lots',Boxes],['Awaiting inspection',state.inspections.filter(i=>i.status==='pending').length,'Completed production batches',Clock3]],
    dispatch:[['Ready for dispatch',state.dispatches.filter(d=>d.delivery_status==='packed').length,'Packed consignments',Boxes],['In transit',state.dispatches.filter(d=>d.delivery_status==='dispatched').length,'Awaiting delivery confirmation',Truck],['Delivered',state.dispatches.filter(d=>d.delivery_status==='delivered').length,'Completed consignments',PackageCheck],['Rings packed',count(sum(state.dispatches,'packed_quantity')),'Inspected quantities allocated',ShoppingBag]],
    finance:[['Order revenue',shortMoney(sum(state.finance,'selling_amount')),'Forecast and realized orders',IndianRupee],['Recorded costs',shortMoney(sum(state.finance,'total_cost')),'Six cost categories combined',Boxes],['Projected contribution',shortMoney(sum(state.finance,'profit_or_loss')),'Revenue less recorded costs',TrendingUp],['Realized contribution',shortMoney(sum(state.finance.filter(f=>f.status==='realized'),'profit_or_loss')),'Delivered orders only',CircleCheck]],
  }[kind];
  const statuses=kind==='orders'?ORDER_STAGES:kind==='inventory'?['available','low_stock']:kind==='production'?['in_progress','completed']:kind==='quality'?['pending','completed']:kind==='dispatch'?['packed','dispatched','delivered']:kind==='finance'?['forecast','realized']:[];
  const csvColumns=columns.filter(c=>c.key!=='action').map(c=>({label:c.title,value:row=>{if(c.key==='company'||c.key==='destination')return customerFor((kind==='orders'?row:orderFor(row.order_id))?.customer_id)?.company_name;if(c.key==='date'||c.key==='due')return row.expected_delivery_date||row.production_date||row.inspection_date||row.start_time||row.delivery_date;if(c.key==='status')return row.stock_status||row.delivery_status||row.status;if(c.key==='machine')return machineFor(row.machine_id)?.machine_name;if(c.key==='quantity'||c.key==='packed')return row.quantity||row.packed_quantity;if(c.key==='order')return row.order_id;if(c.key==='stock')return row.available_quantity-row.reserved_quantity;if(c.key==='reserved')return row.reserved_quantity;if(c.key==='reorder')return row.low_stock_limit;if(c.key==='type')return row.item_type;if(c.key==='checked')return row.quantity_checked;if(c.key==='accepted')return row.accepted_rings;if(c.key==='faulty')return row.faulty_rings;if(c.key==='hours')return row.running_hours;if(c.key==='energy')return row.running_hours*(machineFor(row.machine_id)?.power_rating_kw||0);if(c.key==='output')return row.quantity_produced+'/'+row.target_quantity;if(c.key==='transport')return row.transport_details;if(c.key==='reworked')return row.reworked_quantity+'/'+row.scrap_quantity;if(c.key==='margin')return row.selling_amount?row.profit_or_loss/row.selling_amount*100:0;return row[c.key];}}));
  const [tomorrow]=useState(()=>new Date(Date.now()+7*86400000).toISOString().slice(0,10));const action=modal?.action,row=modal?.row;
  const dialogTitle={createOrder:'Create customer order',createStockItem:'Add stock item',adjustStock:'Adjust stock',createBatch:'Schedule production batch',updateBatch:'Record batch output',recordInspection:'Record quality inspection',createDispatch:'Create dispatch',logRuntime:'Log machine hours',createMachine:'Add machine',updateMachine:'Edit machine',updateCosts:'Record order costs'}[action];
  return <><PageHeader eyebrow={config.eyebrow} title={config.title} description={config.description}>{kind==='machines'&&user.role==='admin'&&<ActionButton onClick={()=>open('createMachine')}>Add machine</ActionButton>}<ExportButton name={kind} rows={filtered} columns={csvColumns}/>{canWrite&&config.add&&<ActionButton primary onClick={()=>open(config.action)}>{config.add}</ActionButton>}</PageHeader><div className="metrics-grid">{metrics.map(([title,value,description,Icon],i)=><Metric key={title} title={title} value={value} detail={description} icon={Icon} tone={['teal','blue','violet','orange'][i]}/>)}</div>{kind==='machines'&&<div className="machine-cards">{state.machines.map(m=><div className="machine-card" key={m.machine_id}><div className="machine-card-heading"><Gauge size={20}/><Status value={m.status}/></div><h3>{m.machine_name}</h3><p>{m.department} · {m.power_rating_kw} kW</p><span>{m.operator_name}</span>{user.role==='admin'&&<button className="table-action" onClick={()=>open('updateMachine',m)}>Edit machine</button>}</div>)}</div>}<Panel title={kind==='machines'?'Runtime log':config.title+' register'} subtitle={filtered.length+' records'}><div className="table-toolbar"><label className="table-search"><Search size={17}/><input aria-label={'Search '+config.title.toLowerCase()} value={search} placeholder={'Search '+config.title.toLowerCase()+'…'} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label>{statuses.length>0&&<select className="filter-select" aria-label="Filter records by status" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="all">All statuses</option>{statuses.map(s=><option value={s} key={s}>{label(s)}</option>)}</select>}<span className="table-result-count">{filtered.length} {filtered.length===1?'record':'records'}</span></div><Table caption={config.title+' records'} rowKey={config.key} rows={shown} columns={columns}/><div className="table-pagination"><span>{filtered.length?'Showing '+(currentPage*8+1)+'–'+Math.min((currentPage+1)*8,filtered.length)+' of '+filtered.length:'No matching records'}</span><div><button className="icon-button" aria-label="Previous page" disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={18}/></button><span>{currentPage+1} / {pageCount}</span><button className="icon-button" aria-label="Next page" disabled={currentPage===pageCount-1} onClick={()=>setPage(currentPage+1)}><ChevronRight size={18}/></button></div></div></Panel>{kind==='dispatch'&&<Panel title="Delivery destinations" subtitle="Factory and customer city locations"><Suspense fallback={<p className="map-loading">Opening destination map…</p>}><DeliveryMap state={state}/></Suspense></Panel>}{kind==='finance'&&<div className="footnote-card"><IndianRupee size={18}/><p>Contribution equals order revenue minus recorded costs. Forecast amounts become realized when the full order quantity is delivered. This view excludes taxes and unrecorded overhead.</p></div>}
  {modal&&<FormDialog key={action+':'+(row?.[config.key]||'new')} open title={dialogTitle} description={action==='recordInspection'?'Accepted and faulty quantities must account for the complete production lot.':'Saved changes are linked to this workspace and recorded in its activity history.'} action={action} onClose={()=>setModal(null)} initialPayload={row?{machine_id:row.machine_id,inventory_id:row.inventory_id,production_id:row.production_id,inspection_id:row.inspection_id,order_id:row.order_id}:{}} submitLabel={action==='createOrder'?'Create order':action==='createBatch'?'Schedule batch':action==='createDispatch'?'Create dispatch':'Save record'}>
    {action==='createOrder'&&<><Field label="Company name" name="company_name" required minLength={2} maxLength={120} placeholder="Customer company"/><Field label="Contact name" name="customer_name" required minLength={2} maxLength={120} placeholder="Contact person"/><Field label="Customer city" name="location" required minLength={2} maxLength={120} list="customer-cities" placeholder="e.g. Chennai"/><datalist id="customer-cities">{['Hyderabad','Chennai','Bengaluru','Pune','Mumbai','Delhi','Warangal'].map(c=><option key={c}>{c}</option>)}</datalist><Select label="Product" name="product_name" value={chosenProduct} onChange={e=>setChosenProduct(e.target.value)} options={state.products.map(p=>({value:p.name,label:p.name}))}/><Field label="Quantity (rings)" name="quantity" type="number" min="1" max="10000000" step="1" required placeholder="e.g. 1500"/><Field key={chosenProduct} label="Unit price (₹)" name="unit_price" type="number" min="0.01" step="0.01" required defaultValue={state.products.find(p=>p.name===chosenProduct)?.price||0}/><Field label="Expected delivery" name="expected_delivery_date" type="date" min={today} required defaultValue={tomorrow}/><Select label="Priority" name="priority" options={[{value:'normal',label:'Normal'},{value:'urgent',label:'Priority'}]}/><Field label="Order notes"><textarea name="notes" maxLength={500} rows={3} placeholder="Specifications or delivery instructions"/></Field></>}
    {action==='createStockItem'&&<><Field label="Item name" name="item_name" required minLength={2} maxLength={120}/><Field label="SKU" name="sku" required minLength={2} maxLength={40}/><Select label="Category" name="item_type" options={['raw_material','finished_product','packing_material'].map(v=>({value:v,label:label(v)}))}/><Select label="Unit" name="unit" options={['kg','pcs','litres','metres'].map(v=>({value:v,label:v}))}/><Field label="Opening stock" name="available_quantity" type="number" min="0" step="0.01" required defaultValue={0}/><Field label="Reorder level" name="low_stock_limit" type="number" min="0" step="0.01" required defaultValue={0}/><Field label="Storage location" name="location" required minLength={2} placeholder="e.g. Raw material · A4"/></>}
    {action==='adjustStock'&&<><div className="form-context"><strong>{row.item_name} · {row.sku}</strong><p>On hand: {count(row.available_quantity)} {row.unit} · Reserved: {count(row.reserved_quantity)} {row.unit}</p></div><Field label={'Stock adjustment ('+row.unit+')'} name="delta" type="number" step="0.01" required placeholder="Positive to receive, negative to issue"/><Field label="Reason" name="reason" minLength={3} maxLength={240} required placeholder="e.g. Purchase receipt or production issue"/></>}
    {['createBatch','createDispatch','logRuntime','updateCosts'].includes(action)&&!row?.order_id&&<Select label="Order" name="order_id" value={selectedOrder} onChange={e=>setChosenOrder(e.target.value)} required options={formOrders.length?formOrders.map(o=>({value:o.order_id,label:'ORD-'+o.order_id+' · '+o.product_name+(action==='createBatch'?' · '+remainingFor(o.order_id)+' remaining':action==='createDispatch'?' · '+approvedFor(o.order_id)+' available':'')})):[{value:'',label:'No eligible orders'}]}/>}
    {['createMachine','updateMachine'].includes(action)&&<><Field label="Machine name" name="machine_name" required minLength={2} defaultValue={row?.machine_name}/><Field label="Department" name="department" required minLength={2} defaultValue={row?.department}/><Field label="Rated power (kW)" name="power_rating_kw" type="number" min="0.1" max="1000" step="0.1" required defaultValue={row?.power_rating_kw||12}/><Field label="Daily capacity (hours)" name="capacity_hours" type="number" min="0.1" max="24" step="0.1" required defaultValue={row?.capacity_hours||8}/><Field label="Operator name" name="operator_name" required minLength={2} defaultValue={row?.operator_name}/><Select label="Status" name="status" defaultValue={row?.status||'active'} options={[{value:'active',label:'Active'},{value:'maintenance',label:'Under maintenance'}]}/></>}
    {action==='createBatch'&&<><Select label="Machine" name="machine_id" required options={state.machines.filter(m=>m.status==='active').map(m=>({value:m.machine_id,label:m.machine_name}))}/><Field label="Operator name" name="operator_name" required minLength={2} maxLength={120}/><Field key={selectedOrder} label="Batch target (rings)" name="target_quantity" type="number" min="1" max={Math.max(1,remainingFor(selectedOrder))} step="1" required defaultValue={Math.max(1,remainingFor(selectedOrder))}/><p className="form-help">Batch targets are checked against the remaining order quantity.</p></>}
    {action==='updateBatch'&&<><div className="form-context"><strong>LOT-{row.production_id} · ORD-{row.order_id}</strong><p>{count(row.quantity_produced)} produced of {count(row.target_quantity)} rings</p></div><Field label="Additional rings produced" name="quantity" type="number" min="1" max={row.target_quantity-row.quantity_produced} step="1" required defaultValue={row.target_quantity-row.quantity_produced}/><p className="form-help">Reaching the batch target completes the lot and creates its pending inspection.</p></>}
    {action==='recordInspection'&&<><div className="form-context"><strong>QC-{row.inspection_id} · LOT-{row.production_id}</strong><p>Inspect all {count(state.production.find(p=>p.production_id===row.production_id)?.quantity_produced)} rings in this lot.</p></div><Field label="Accepted rings" name="accepted_rings" type="number" min="0" step="1" required defaultValue={state.production.find(p=>p.production_id===row.production_id)?.quantity_produced||0}/><Field label="Faulty rings" name="faulty_rings" type="number" min="0" step="1" required defaultValue={0}/><Field label="Recovered through rework" name="reworked_quantity" type="number" min="0" step="1" required defaultValue={0}/><Field label="Scrapped rings" name="scrap_quantity" type="number" min="0" step="1" required defaultValue={0}/><Field label="Inspector name" name="inspector_name" required minLength={2} maxLength={120}/><Field label="Inspection remarks" name="remarks" minLength={2} maxLength={500} defaultValue="Dimensions and surface finish within tolerance"/></>}
    {action==='createDispatch'&&<><Field key={selectedOrder} label="Packed rings" name="packed_quantity" type="number" min="1" max={Math.max(1,approvedFor(selectedOrder))} step="1" required defaultValue={Math.max(1,approvedFor(selectedOrder))}/><Field label="Transport / vehicle details" name="transport_details" required minLength={3} maxLength={240} placeholder="Logistics partner and vehicle number"/><Field label="Tracking reference" name="tracking_reference" required minLength={2} maxLength={80}/><p className="form-help">Only inspected, accepted rings and recovered rework can be allocated to a dispatch.</p></>}
    {action==='logRuntime'&&<><Select label="Machine" name="machine_id" required options={state.machines.filter(m=>m.status==='active').map(m=>({value:m.machine_id,label:m.machine_name}))}/><Field label="Operator name" name="operator_name" required minLength={2} maxLength={120}/><Field label="Running hours" name="running_hours" type="number" min="0.1" max="24" step="0.1" required placeholder="e.g. 3.5"/><p className="form-help">Records a run ending now. Energy is calculated from hours and rated power.</p></>}
    {action==='updateCosts'&&<>{row&&<div className="form-context"><strong>ORD-{row.order_id}</strong><p>Order revenue: {rupees(orderFor(row.order_id)?.total_amount)}</p></div>}{COST_FIELDS.map(field=><Field key={field+':'+selectedOrder} label={label(field)+' (₹)'} name={field} type="number" min="0" step="0.01" required defaultValue={row?.[field]??state.finance.find(f=>f.order_id===selectedOrder)?.[field]??0}/>)}<p className="form-help">Total cost and contribution are recalculated from these entries. One cost sheet is kept per order.</p></>}
  </FormDialog>}{detail&&<OrderDetails order={detail} customer={customerFor(detail.customer_id)} onClose={()=>setDetail(null)}/>}<ConfirmDialog open={!!confirmation} title={confirmation?.delivery_status==='packed'?'Confirm this dispatch?':'Confirm completed delivery?'} description={confirmation?'DSP-'+confirmation.dispatch_id+' · '+count(confirmation.packed_quantity)+' rings. This records the '+(confirmation.delivery_status==='packed'?'dispatch':'delivery')+' date and updates its linked order.':''} onClose={()=>setConfirmation(null)} onConfirm={async()=>{try{await perform('advanceDispatch',{dispatch_id:confirmation.dispatch_id});}catch(e){notify(e.message,'error');throw e;}}}/></>;
}
